[project]
name = "vizdat-mid"
version = "0.1.0"

requires-python = ">=3.13" 

dependencies = [
    "streamlit",
    "openpyxl"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"